# -*- coding: utf-8 -*-
"""Ejercicio1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-oPOwCVZIznS-5xjEs1H0ffv5iDWNG2
"""

# Objetivo: Area de un rectangulo
# Nombre: LAZO VILLODAS, ALEJANDRO
# Fecha: 30/04/1996
# ENTRADA
base=float(input("Ingrese la base: "))
altura=float(input("INgrese la altura: "))
# PROCESO
Calcular = base * altura
# SALIDA
print("El area del rectangulo con los datos ingresados es: ", Calcular)

# Objetivo: VOLUMEN DE UN CUBO
# Nombre: LAZO VILLODAS, ALEJANDRO
# Fecha: 30/04/1996
# ENTRADA
LADO=int(input("Ingrese el lado:"))
# PROCESO
Calcular = LADO ** 3
# SALIDA
print("Ek Volumen con los datos ingresados es: ", Calcular)